# Generated by Django 4.2.6 on 2024-05-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evemuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
