# Generated by Django 4.2.6 on 2024-05-15 07:41

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_evemuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evemuser',
            name='username',
            field=models.CharField(db_collation='utf8mb4_bin', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
