# Generated by Django 4.2.6 on 2024-05-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_evemuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evemuser',
            name='eve_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
