# Generated by Django 4.2.5 on 2024-06-06 13:43

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_evemuser_eve_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.BigIntegerField(default=time.time)),
            ],
            options={
                'db_table': 'email_code',
            },
        ),
        migrations.AlterModelOptions(
            name='evemuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='evemuser',
            table='authentication_evemuser',
        ),
    ]
