# Generated by Django 4.2.5 on 2026-09-28 21:04

import Killboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('min_ship_rank', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('allowed_class_keys', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProbeCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=80, unique=True)),
                ('last_success_id', models.BigIntegerField(blank=True, null=True)),
                ('last_success_kill_time', models.DateTimeField(blank=True, null=True)),
                ('consecutive_empty_count', models.PositiveIntegerField(default=0)),
                ('next_probe_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at_ms', models.BigIntegerField(default=Killboard.models.epoch_ms)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShipClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('rank', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('enabled', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['rank', 'key'],
                'indexes': [models.Index(fields=['enabled', 'rank'], name='kb_shipclass_enabled_rank')],
            },
        ),
        migrations.CreateModel(
            name='ProbeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('stopped', 'Stopped'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('started_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('finished_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('empty_count', models.PositiveIntegerField(default=0)),
                ('stop_reason', models.CharField(blank=True, default='', max_length=64)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at_ms', models.BigIntegerField(db_index=True, default=Killboard.models.epoch_ms)),
                ('cursor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='Killboard.probecursor')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='Killboard.collectionpolicy')),
            ],
            options={
                'ordering': ['-created_at_ms', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KillReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_id', models.BigIntegerField(unique=True)),
                ('ship_type_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('ship_name', models.CharField(blank=True, default='', max_length=255)),
                ('ship_class_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ship_class_label', models.CharField(blank=True, default='', max_length=120)),
                ('system_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('system_name', models.CharField(blank=True, default='', max_length=255)),
                ('victim_character_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('victim_name', models.CharField(blank=True, default='', max_length=255)),
                ('victim_corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('victim_corporation_name', models.CharField(blank=True, default='', max_length=255)),
                ('victim_alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('victim_alliance_name', models.CharField(blank=True, default='', max_length=255)),
                ('kill_time_raw', models.CharField(blank=True, default='', max_length=64)),
                ('kill_time_display', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('time_quality', models.CharField(choices=[('source', 'Source timestamp'), ('converted', 'Converted timestamp'), ('unknown', 'Unknown timestamp')], default='unknown', max_length=16)),
                ('isk_lost', models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True)),
                ('participant_count', models.PositiveIntegerField(blank=True, null=True)),
                ('participant_count_source', models.CharField(default='unknown', max_length=32)),
                ('source', models.CharField(db_index=True, default='unknown', max_length=64)),
                ('parser_version', models.CharField(default='1', max_length=32)),
                ('completeness', models.CharField(choices=[('partial', 'Partial'), ('complete', 'Complete'), ('needs_review', 'Needs review')], db_index=True, default='partial', max_length=16)),
                ('raw_hash', models.CharField(blank=True, default='', max_length=128)),
                ('collected_at_ms', models.BigIntegerField(db_index=True, default=Killboard.models.epoch_ms)),
                ('updated_at_ms', models.BigIntegerField(default=Killboard.models.epoch_ms)),
            ],
            options={
                'ordering': ['-kill_time_display', '-kill_id'],
                'indexes': [models.Index(fields=['ship_class_key', '-kill_time_display'], name='kb_report_ship_time'), models.Index(fields=['system_id', '-kill_time_display'], name='kb_report_system_time'), models.Index(fields=['victim_character_id', '-kill_time_display'], name='kb_report_char_time'), models.Index(fields=['completeness', '-updated_at_ms'], name='kb_report_complete_updated')],
            },
        ),
        migrations.CreateModel(
            name='KillParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('character_name', models.CharField(blank=True, default='', max_length=255)),
                ('corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('corporation_name', models.CharField(blank=True, default='', max_length=255)),
                ('alliance_id', models.BigIntegerField(blank=True, null=True)),
                ('alliance_name', models.CharField(blank=True, default='', max_length=255)),
                ('damage', models.PositiveBigIntegerField(blank=True, null=True)),
                ('damage_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('is_final_blow', models.BooleanField(default=False)),
                ('is_top_damage', models.BooleanField(default=False)),
                ('source_index', models.PositiveIntegerField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Killboard.killreport')),
            ],
            options={
                'ordering': ['source_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('slot', models.CharField(blank=True, default='', max_length=64)),
                ('quantity_dropped', models.PositiveBigIntegerField(default=0)),
                ('quantity_destroyed', models.PositiveBigIntegerField(default=0)),
                ('quantity_unknown', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('dropped', 'Dropped'), ('destroyed', 'Destroyed'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Killboard.killreport')),
            ],
            options={
                'ordering': ['slot', 'name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='collectionpolicy',
            index=models.Index(fields=['enabled', 'min_ship_rank'], name='kb_policy_enabled_rank'),
        ),
        migrations.AddIndex(
            model_name='proberun',
            index=models.Index(fields=['status', '-created_at_ms'], name='kb_probe_status_created'),
        ),
        migrations.AddIndex(
            model_name='killparticipant',
            index=models.Index(fields=['report', 'is_final_blow'], name='kb_participant_final'),
        ),
        migrations.AddIndex(
            model_name='killparticipant',
            index=models.Index(fields=['report', 'is_top_damage'], name='kb_participant_top'),
        ),
        migrations.AddIndex(
            model_name='killparticipant',
            index=models.Index(fields=['character_id', 'report'], name='kb_participant_char_report'),
        ),
        migrations.AddIndex(
            model_name='killitem',
            index=models.Index(fields=['report', 'status'], name='kb_item_report_status'),
        ),
        migrations.AddIndex(
            model_name='killitem',
            index=models.Index(fields=['type_id', 'status'], name='kb_item_type_status'),
        ),
        migrations.AddConstraint(
            model_name='killitem',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ('dropped', 'destroyed', 'mixed', 'unknown'))), name='kb_item_status_valid'),
        ),
    ]
