# Generated by Django 4.2.5 on 2026-09-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Killboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='killparticipant',
            name='ship_type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='killparticipant',
            name='weapon_type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='killreport',
            name='equipment_status',
            field=models.CharField(default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='killreport',
            name='participants_status',
            field=models.CharField(default='unknown', max_length=16),
        ),
    ]
