# Generated by Django 4.2.5 on 2026-09-30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Killboard', '0002_killparticipant_ship_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpolicy',
            name='min_isk_lost',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=24,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name='proberun',
            name='lease_expires_at_ms',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='proberun',
            name='lease_owner',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
