# Generated by Django 4.2.5 on 2026-09-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Killboard', '0003_collectionpolicy_min_isk_and_probe_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='probecursor',
            name='candidate_at_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='probecursor',
            name='candidate_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='probecursor',
            name='cooldown_until_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='probecursor',
            name='failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='probecursor',
            name='pause_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
