# Generated by Django 4.2.5 on 2026-09-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Killboard', '0004_probecursor_candidate_at_ms_probecursor_candidate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probecursor',
            name='provisional_empty_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
