# Generated by Django 4.2.5 on 2026-09-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Killboard', '0005_probecursor_provisional_empty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='killparticipant',
            name='camouflaged_faction_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='killparticipant',
            name='feat_score',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='killparticipant',
            name='is_source_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='killreport',
            name='damage_total_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='killreport',
            name='final_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='killreport',
            name='victim_damage_taken',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
