# Generated by Django 4.2.5 on 2026-10-01

import Killboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Killboard', '0006_killparticipant_camouflaged_faction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(db_index=True, max_length=24)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('observed_at_ms', models.BigIntegerField(db_index=True, default=Killboard.models.epoch_ms)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Killboard.proberun')),
            ],
            options={
                'ordering': ['-observed_at_ms', '-id'],
                'indexes': [
                    models.Index(fields=['run', '-observed_at_ms'], name='kb_probeevent_run_time'),
                    models.Index(fields=['status', '-observed_at_ms'], name='kb_probeevent_status_time'),
                ],
            },
        ),
    ]
