import { test, expect } from '@playwright/test'
import { installApiMock, json } from '../helpers/api'
import { createFakeJwt } from '../helpers/auth'

test('认证标签使用单个 Tab 停靠点并支持方向键 Home End', async ({ page }) => {
  await installApiMock(page, async () => json({ duplicate: null }))
  await page.goto('/login')
  const tabs = page.getByRole('tablist', { name: '认证模式' })
  const loginTab = tabs.getByRole('tab', { name: '登录', exact: true })
  const registerTab = tabs.getByRole('tab', { name: '注册', exact: true })
  const resetTab = tabs.getByRole('tab', { name: '找回密码', exact: true })
  await expect(loginTab).toHaveAttribute('tabindex', '0')
  await expect(registerTab).toHaveAttribute('tabindex', '-1')
  await loginTab.focus()
  await page.keyboard.press('ArrowRight')
  await expect(registerTab).toBeFocused()
  await expect(registerTab).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tabpanel', { name: '注册', exact: true })).toBeVisible()
  await expect(loginTab).toHaveAttribute('tabindex', '-1')
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('用户名', { exact: true })).toBeFocused()
  await registerTab.focus()
  await page.keyboard.press('End')
  await expect(resetTab).toBeFocused()
  await page.keyboard.press('ArrowRight')
  await expect(loginTab).toBeFocused()
  await page.keyboard.press('ArrowLeft')
  await expect(resetTab).toBeFocused()
  await page.keyboard.press('Home')
  await expect(loginTab).toBeFocused()
})

test('表单标签与错误关联且无效提交聚焦首个字段', async ({ page }) => {
  await page.goto('/login')
  const email = page.getByLabel('邮箱', { exact: true })
  const password = page.getByLabel('密码', { exact: true })
  await expect(email).toHaveAttribute('autocomplete', 'username')
  await expect(password).toHaveAttribute('autocomplete', 'current-password')
  await page.getByRole('tabpanel').getByRole('button', { name: '登录', exact: true }).click()
  await expect(email).toBeFocused()
  await expect(email).toHaveAttribute('aria-invalid', 'true')
  await expect(email).toHaveAttribute('aria-describedby', 'login-email-error')
  await expect(page.locator('#login-email-error')).toHaveText('请输入邮箱')
  await email.fill('pilot@example.com')
  await expect(email).toHaveAttribute('aria-invalid', 'false')
  await expect(email).not.toHaveAttribute('aria-describedby')
  await page.getByRole('tabpanel').getByRole('button', { name: '登录', exact: true }).click()
  await expect(password).toBeFocused()
  await expect(password).toHaveAttribute('aria-describedby', 'login-password-error')
  await page.getByRole('tab', { name: '找回密码', exact: true }).click()
  await expect(page.getByLabel('邮箱验证码', { exact: true })).toHaveAttribute('autocomplete', 'one-time-code')
  await expect(page.getByLabel('新密码', { exact: true })).toHaveAttribute('autocomplete', 'new-password')
  await expect(page.getByLabel('新密码', { exact: true })).toHaveAttribute('aria-describedby', 'reset-password-hint')
})

test('鉴权入口说明原因且登录后恢复原页面', async ({ page }) => {
  const token = createFakeJwt({ userName: 'returning_pilot' })
  await installApiMock(page, async ({ url, method }) => {
    if (method === 'POST' && url.pathname === '/api/user/login') return json({ access: token, refresh: token })
    return json([])
  })
  await page.goto('/usersetting')
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole('status')).toHaveText('此页面需要登录。完成登录后将返回刚才的页面。')
  await page.getByLabel('邮箱', { exact: true }).fill('pilot@example.com')
  await page.getByLabel('密码', { exact: true }).fill('Password_123')
  await page.getByRole('tabpanel').getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).toHaveURL(/\/usersetting$/)
  await expect(page.getByRole('heading', { name: '修改密码' })).toBeVisible()
})

test('登录返回参数无法将浏览器带离站内', async ({ page }) => {
  const token = createFakeJwt()
  await installApiMock(page, async ({ url, method }) => {
    if (method === 'POST' && url.pathname === '/api/user/login') return json({ access: token, refresh: token })
    return json([])
  })
  await page.goto('/login?next=https%3A%2F%2Fevil.test')
  await page.getByLabel('邮箱', { exact: true }).fill('pilot@example.com')
  await page.getByLabel('密码', { exact: true }).fill('Password_123')
  await page.getByRole('tabpanel').getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).toHaveURL(/\/fraudlist$/)
})

test('减少动态效果偏好使登录入口稳定显示', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/login')
  await expect(page.locator('.login-card')).toHaveCSS('transform', 'none')
  await expect(page.locator('.login-card')).toHaveCSS('opacity', '1')
})
