import { useCallback, useEffect, useMemo, useState } from 'react'
import { normalizeClientIconMapping } from '../utils/clientIconMapping'

export const STORAGE_KEY = 'evem:client-icon-verification:v1'
export const EMPTY_MANIFEST_MESSAGE = '没有找到候选图标。请先运行 icons:prepare 生成本地候选清单。'
export const CANDIDATE_ROOT = '/dev/icon-candidates/'
const SHA256_PATTERN = /^[a-f0-9]{64}$/iu
const SAFE_RELATIVE_PATH = /^(?!\/)(?!.*(?:^|\/)\.\.?(?:\/|$))(?!.*[\\?#])[A-Za-z0-9._/-]+$/u
const PAGE_SIZE = 24

function normalizedId(value) {
  const id = String(value ?? '').trim()
  return /^[1-9][0-9]*$/u.test(id) ? id : null
}

function safeText(value) {
  return typeof value === 'string' ? value.trim() : ''
}

function safeTimestamp(value) {
  const timestamp = safeText(value)
  return timestamp || new Date().toISOString()
}

/** Keep candidate previews constrained to files generated by icons:prepare. */
export function normalizeCandidateForUi(candidate) {
  if (!candidate || typeof candidate !== 'object' || Array.isArray(candidate)) return null
  const sourceHash = safeText(candidate.sourceHash).toLowerCase()
  const source = safeText(candidate.source)
  const png = safeText(candidate.png)
  const thumbnailUrl = safeText(candidate.thumbnailUrl)
  const format = safeText(candidate.format).toLowerCase()
  const width = Number(candidate.width)
  const height = Number(candidate.height)
  if (!SHA256_PATTERN.test(sourceHash) || !source || !SAFE_RELATIVE_PATH.test(source) || !SAFE_RELATIVE_PATH.test(png)) return null
  if (format !== 'png' || !Number.isSafeInteger(width) || !Number.isSafeInteger(height) || width < 16 || height < 16 || width !== height) return null
  if (thumbnailUrl !== `thumbnails/${sourceHash}.webp`) return null
  const iconId = candidate.iconId === undefined || candidate.iconId === null || candidate.iconId === '' ? null : String(candidate.iconId)
  return { source, sourceHash, png, width, height, format, thumbnailUrl, ...(iconId ? { iconId } : {}) }
}

export function filterCandidates(candidates, filters = {}) {
  const query = safeText(filters.query).toLowerCase()
  const source = safeText(filters.source).toLowerCase()
  const format = safeText(filters.format).toLowerCase()
  const minDimension = Number(filters.minDimension || 0)
  const maxDimension = Number(filters.maxDimension || Number.POSITIVE_INFINITY)
  return (Array.isArray(candidates) ? candidates : [])
    .map(normalizeCandidateForUi)
    .filter(Boolean)
    .filter(candidate => {
      const haystack = `${candidate.source} ${candidate.png} ${candidate.sourceHash} ${candidate.iconId || ''}`.toLowerCase()
      return (!query || haystack.includes(query)) &&
        (!source || candidate.source.toLowerCase().includes(source) || candidate.png.toLowerCase().includes(source)) &&
        (!format || candidate.format === format) &&
        candidate.width >= minDimension && candidate.width <= maxDimension
    })
}

export function filterCatalogItems(items, filters = {}) {
  const query = safeText(filters.query).toLowerCase()
  const category = safeText(filters.category).toLowerCase()
  const statuses = filters.statuses instanceof Set ? filters.statuses : null
  return (Array.isArray(items) ? items : []).filter(item => {
    const itemId = normalizedId(item?.itemId)
    if (!itemId) return false
    const name = safeText(item.name)
    const itemCategory = safeText(item.category).toLowerCase()
    const status = safeText(filters.statusMap?.[itemId] || 'unmapped').toLowerCase()
    return (!query || `${name} ${itemId}`.toLowerCase().includes(query)) &&
      (!category || itemCategory === category) &&
      (!statuses || statuses.has(status))
  })
}

function existingValues(bindings) {
  if (bindings instanceof Map) return [...bindings.values()]
  if (!bindings || typeof bindings !== 'object') return []
  return Object.values(bindings)
}

function normalizeBinding(binding) {
  if (!binding || typeof binding !== 'object') return null
  const itemId = normalizedId(binding.itemId)
  const sourceHash = safeText(binding.sourceHash).toLowerCase()
  const iconPath = safeText(binding.iconPath)
  if (!itemId || !SHA256_PATTERN.test(sourceHash) || !/^\/images\/client-items\/[1-9][0-9]*\.(?:png|webp)$/u.test(iconPath)) return null
  const width = Number(binding.width)
  const height = Number(binding.height)
  if (!Number.isSafeInteger(width) || !Number.isSafeInteger(height) || width <= 0 || height <= 0) return null
  return {
    itemId,
    iconId: binding.iconId === null || binding.iconId === undefined || binding.iconId === '' ? null : String(binding.iconId),
    iconPath,
    sourceHash,
    width,
    height,
    format: safeText(binding.format).toLowerCase() || 'png',
    status: ['confirmed', 'conflict', 'revoked'].includes(binding.status) ? binding.status : 'confirmed',
    confirmedAt: safeTimestamp(binding.confirmedAt),
  }
}

export function createBinding({ item, candidate, existingBindings = {}, now } = {}) {
  const itemId = normalizedId(item?.itemId)
  const normalizedCandidate = normalizeCandidateForUi(candidate)
  if (!itemId || !normalizedCandidate) return { ok: false, reason: 'invalid' }
  const bindings = existingValues(existingBindings)
    .map(binding => normalizeBinding(binding) || {
      itemId: normalizedId(binding?.itemId),
      sourceHash: safeText(binding?.sourceHash).toLowerCase(),
      status: binding?.status === 'revoked' ? 'revoked' : 'confirmed',
    })
    .filter(binding => binding.itemId && SHA256_PATTERN.test(binding.sourceHash))
  const itemBinding = bindings.find(binding => binding.itemId === itemId && binding.status !== 'revoked')
  const candidateBinding = bindings.find(binding => binding.sourceHash === normalizedCandidate.sourceHash && binding.status !== 'revoked')
  if ((itemBinding && itemBinding.sourceHash !== normalizedCandidate.sourceHash) || (candidateBinding && candidateBinding.itemId !== itemId)) {
    return { ok: false, reason: 'conflict', existing: itemBinding || candidateBinding }
  }
  const binding = {
    itemId,
    iconId: normalizedCandidate.iconId || null,
    iconPath: `/images/client-items/${itemId}.png`,
    sourceHash: normalizedCandidate.sourceHash,
    width: normalizedCandidate.width,
    height: normalizedCandidate.height,
    format: normalizedCandidate.format,
    status: 'confirmed',
    confirmedAt: safeTimestamp(now),
  }
  return { ok: true, binding }
}

export function revokeBinding({ binding, itemId } = {}) {
  const normalized = normalizeBinding(binding)
  if (!normalized || !normalizedId(itemId || normalized.itemId)) return null
  return { ...normalized, itemId: normalizedId(itemId || normalized.itemId), status: 'revoked' }
}

export function buildExportPayload(bindings = {}) {
  const rawBindings = existingValues(bindings)
  const mappings = rawBindings
    .map(normalizeBinding)
  if (mappings.some(mapping => !mapping)) throw new TypeError('Invalid draft binding')
  const normalizedMappings = mappings
    .sort((left, right) => left.itemId.localeCompare(right.itemId))
  const payload = { schemaVersion: 1, mappings: normalizedMappings }
  // Reuse the production schema validator so a downloaded draft can be consumed safely.
  const normalized = normalizeClientIconMapping(payload)
  return { schemaVersion: normalized.schemaVersion, mappings: normalized.mappings }
}

function loadStoredBindings() {
  if (typeof window === 'undefined' || !window.localStorage) return {}
  try {
    const parsed = JSON.parse(window.localStorage.getItem(STORAGE_KEY) || '{}')
    return normalizeStoredBindings(parsed)
  } catch {
    return {}
  }
}

export function normalizeStoredBindings(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {}
  return Object.fromEntries(Object.entries(value).map(([key, binding]) => [key, normalizeBinding(binding)]).filter(([, binding]) => binding))
}

function saveStoredBindings(bindings) {
  try { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(bindings)) } catch { /* storage is optional in private browsing */ }
}

export function catalogItemsFromSource(source) {
  const byId = new Map()
  for (const item of Array.isArray(source?.items) ? source.items : []) {
    const itemId = normalizedId(item?.itemId)
    const name = safeText(item?.name)
    if (itemId && name) byId.set(itemId, { itemId, name, category: safeText(item.category) || 'material' })
  }
  for (const recipe of Array.isArray(source?.recipes) ? source.recipes : []) {
    const itemId = normalizedId(recipe?.productId)
    const name = safeText(recipe?.name)
    if (itemId && name) byId.set(itemId, { itemId, name, category: safeText(recipe.category) || byId.get(itemId)?.category || 'material' })
  }
  return [...byId.values()].sort((left, right) => left.name.localeCompare(right.name, 'zh-CN') || left.itemId.localeCompare(right.itemId))
}

function manifestCandidates(source) {
  const entries = Array.isArray(source) ? source : source?.candidates
  return Array.isArray(entries) ? entries.map(normalizeCandidateForUi).filter(Boolean) : []
}

function exportJson(payload) {
  if (typeof document === 'undefined' || typeof URL === 'undefined') return
  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'confirmed-client-icon-mapping.json'
  link.click()
  setTimeout(() => URL.revokeObjectURL(url), 0)
}

export default function IconVerification() {
  const [catalog, setCatalog] = useState([])
  const [candidates, setCandidates] = useState([])
  const [selectedItemId, setSelectedItemId] = useState('')
  const [selectedCandidateHash, setSelectedCandidateHash] = useState('')
  const [bindings, setBindings] = useState(loadStoredBindings)
  const [itemQuery, setItemQuery] = useState('')
  const [itemCategory, setItemCategory] = useState('')
  const [candidateQuery, setCandidateQuery] = useState('')
  const [candidateSource, setCandidateSource] = useState('')
  const [candidateFormat, setCandidateFormat] = useState('')
  const [candidateMinDimension, setCandidateMinDimension] = useState('')
  const [itemStatus, setItemStatus] = useState('')
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')

  const loadData = useCallback(async () => {
    setLoading(true)
    setError('')
    const [catalogResult, manifestResult] = await Promise.allSettled([
      fetch('/industry/manufacturing-scope.json', { cache: 'no-store' }).then(response => response.ok ? response.json() : Promise.reject(new Error(`catalog ${response.status}`))),
      fetch('/dev/icon-candidates/manifest.json', { cache: 'no-store' }).then(response => response.ok ? response.json() : { candidates: [] }),
    ])
    if (catalogResult.status === 'fulfilled') setCatalog(catalogItemsFromSource(catalogResult.value))
    else setError('制造目录暂时无法加载，请检查开发服务器资源。')
    setCandidates(manifestResult.status === 'fulfilled' ? manifestCandidates(manifestResult.value) : [])
    setLoading(false)
  }, [])

  useEffect(() => { loadData() }, [loadData])
  useEffect(() => { saveStoredBindings(bindings) }, [bindings])

  const statusMap = useMemo(() => Object.fromEntries(Object.values(bindings).map(binding => [binding.itemId, binding.status])), [bindings])
  const filteredItems = useMemo(() => filterCatalogItems(catalog, { query: itemQuery, category: itemCategory, statuses: itemStatus ? new Set([itemStatus]) : null, statusMap }), [catalog, itemQuery, itemCategory, itemStatus, statusMap])
  const filteredCandidates = useMemo(() => filterCandidates(candidates, { query: candidateQuery, source: candidateSource, format: candidateFormat, minDimension: candidateMinDimension }), [candidates, candidateQuery, candidateSource, candidateFormat, candidateMinDimension])
  const pagedCandidates = useMemo(() => filteredCandidates.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE), [filteredCandidates, page])
  const selectedItem = catalog.find(item => item.itemId === selectedItemId) || null
  const selectedCandidate = candidates.find(candidate => candidate.sourceHash === selectedCandidateHash) || null
  const selectedBinding = selectedItem ? bindings[selectedItem.itemId] : null

  useEffect(() => { setPage(1) }, [candidateQuery, candidateSource, candidateFormat, candidateMinDimension])
  useEffect(() => {
    if (!selectedItemId && filteredItems[0]) setSelectedItemId(filteredItems[0].itemId)
    if (selectedItemId && !filteredItems.some(item => item.itemId === selectedItemId)) setSelectedItemId(filteredItems[0]?.itemId || '')
  }, [catalog, filteredItems, selectedItemId])

  function handleBind() {
    const result = createBinding({ item: selectedItem, candidate: selectedCandidate, existingBindings: bindings })
    if (!result.ok) {
      setNotice(result.reason === 'conflict' ? '冲突：该物品或候选图标已有绑定，未静默覆盖。' : '请选择有效物品和候选图标。')
      return
    }
    setBindings(current => ({ ...current, [result.binding.itemId]: result.binding }))
    setNotice('已创建待审查绑定，可导出 JSON 供代码审查。')
  }

  function handleRevoke() {
    if (!selectedBinding || !selectedItem) return
    setBindings(current => ({ ...current, [selectedItem.itemId]: revokeBinding({ binding: selectedBinding, itemId: selectedItem.itemId }) }))
    setNotice('绑定已撤销。')
  }

  function handleExport() {
    try {
      const payload = buildExportPayload(bindings)
      exportJson(payload)
      setNotice(`已导出 ${payload.mappings.length} 条映射。`)
    } catch (exportError) {
      setNotice(`导出失败：${exportError.message}`)
    }
  }

  return (
    <main className="icon-verification-page">
      <header className="icon-verification-header">
        <div><p className="section-kicker">Developer only</p><h1>客户端图标校验</h1><p>人工确认候选图标，导出可审查的生产映射。</p></div>
        <div className="icon-verification-actions"><button type="button" className="ghost-btn" onClick={loadData}>重新加载</button><button type="button" className="primary-btn" onClick={handleExport}>导出映射 JSON</button></div>
      </header>
      {error && <p className="icon-verification-alert is-error">{error}</p>}
      {notice && <p className="icon-verification-alert">{notice}</p>}
      <div className="icon-verification-grid">
        <section className="icon-verification-pane" aria-label="物品目录">
          <div className="panel-head"><div><h2>物品目录</h2><p>{filteredItems.length} 个物品</p></div></div>
          <input className="text-input" aria-label="搜索物品" value={itemQuery} onChange={event => setItemQuery(event.target.value)} placeholder="搜索名称或 ID" />
          <div className="icon-verification-filters"><select className="text-input" aria-label="物品分类" value={itemCategory} onChange={event => setItemCategory(event.target.value)}><option value="">全部分类</option><option value="ship">舰船</option><option value="material">材料</option><option value="building">建筑</option></select><select className="text-input" aria-label="绑定状态" value={itemStatus} onChange={event => setItemStatus(event.target.value)}><option value="">全部状态</option><option value="unmapped">未绑定</option><option value="confirmed">已确认</option><option value="conflict">冲突</option><option value="revoked">已撤销</option></select></div>
          <div className="icon-verification-list">{filteredItems.map(item => <button key={item.itemId} type="button" aria-pressed={selectedItemId === item.itemId} className={`icon-item-row ${selectedItemId === item.itemId ? 'is-selected' : ''}`} onClick={() => setSelectedItemId(item.itemId)}><strong>{item.name}</strong><span>{item.category}</span></button>)}</div>
        </section>
        <section className="icon-verification-pane" aria-label="候选图标">
          <div className="panel-head"><div><h2>候选图标</h2><p>{filteredCandidates.length} 个候选</p></div></div>
          <div className="icon-verification-filters"><input className="text-input" aria-label="搜索候选" value={candidateQuery} onChange={event => setCandidateQuery(event.target.value)} placeholder="搜索哈希、来源或图标 ID" /><input className="text-input" aria-label="来源目录" value={candidateSource} onChange={event => setCandidateSource(event.target.value)} placeholder="来源目录" /><select className="text-input" aria-label="候选格式" value={candidateFormat} onChange={event => setCandidateFormat(event.target.value)}><option value="">全部格式</option><option value="png">PNG</option></select><select className="text-input" aria-label="最小尺寸" value={candidateMinDimension} onChange={event => setCandidateMinDimension(event.target.value)}><option value="">全部尺寸</option><option value="96">≥ 96px</option><option value="128">≥ 128px</option><option value="256">≥ 256px</option></select></div>
          {loading ? <p className="empty-state">正在加载候选清单…</p> : filteredCandidates.length === 0 ? <p className="empty-state">{EMPTY_MANIFEST_MESSAGE}</p> : <><div className="icon-candidate-grid">{pagedCandidates.map(candidate => <button key={candidate.sourceHash} type="button" aria-pressed={selectedCandidateHash === candidate.sourceHash} className={`icon-candidate-card ${selectedCandidateHash === candidate.sourceHash ? 'is-selected' : ''}`} onClick={() => setSelectedCandidateHash(candidate.sourceHash)}><img src={`${CANDIDATE_ROOT}${candidate.thumbnailUrl}`} loading="lazy" alt="" /><strong>{candidate.sourceHash.slice(0, 10)}…</strong><span>{candidate.width} × {candidate.height} · {candidate.format}</span><small>{candidate.source}</small></button>)}</div><div className="icon-verification-pagination"><button type="button" className="ghost-btn" disabled={page <= 1} onClick={() => setPage(current => current - 1)}>上一页</button><span>第 {page} 页</span><button type="button" className="ghost-btn" disabled={page * PAGE_SIZE >= filteredCandidates.length} onClick={() => setPage(current => current + 1)}>下一页</button></div></>}
        </section>
        <aside className="icon-verification-pane icon-verification-inspector" aria-label="绑定检查器">
          <div className="panel-head"><div><h2>绑定检查器</h2><p>仅在这里显示内部 ID</p></div></div>
          {selectedItem ? <><h3>{selectedItem.name}</h3><dl className="icon-binding-meta"><div><dt>Item ID</dt><dd>{selectedItem.itemId}</dd></div><div><dt>状态</dt><dd>{selectedBinding?.status || 'unmapped'}</dd></div></dl>{selectedBinding && <div className="icon-current-binding"><p>当前来源哈希：<code>{selectedBinding.sourceHash}</code></p><p>生产路径：<code>{selectedBinding.iconPath}</code></p><button type="button" className="ghost-btn" onClick={handleRevoke} disabled={selectedBinding.status === 'revoked'}>撤销绑定</button></div>}{selectedCandidate && <div className="icon-selected-candidate"><img src={`${CANDIDATE_ROOT}${selectedCandidate.thumbnailUrl}`} alt="" /><p>{selectedCandidate.source}</p><p><code>{selectedCandidate.sourceHash}</code></p><button type="button" className="primary-btn" onClick={handleBind}>绑定候选图标</button></div>}</> : <p className="empty-state">选择一个物品开始检查。</p>}
        </aside>
      </div>
    </main>
  )
}
