# Generated by Django 4.2.5 on 2026-09-21 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Force',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=80)),
                ('side', models.CharField(max_length=8)),
                ('system_id', models.PositiveIntegerField()),
                ('system_name', models.CharField(max_length=255)),
                ('people', models.PositiveIntegerField(null=True)),
                ('ships', models.JSONField(default=dict)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('observed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('region_ids', models.JSONField(default=list)),
                ('border_hops', models.PositiveSmallIntegerField(default=0)),
                ('scope_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('system_id', models.PositiveIntegerField()),
                ('system_name', models.CharField(max_length=255)),
                ('people', models.PositiveIntegerField(null=True)),
                ('ships', models.JSONField(default=dict)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('observed_at', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TacticalCollaboration.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TacticalCollaboration.report')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='scout', max_length=12)),
                ('status', models.CharField(default='active', max_length=12)),
                ('permission_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TacticalCollaboration.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JoinApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TacticalCollaboration.organization')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TacticalCollaboration.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ForceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('force', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TacticalCollaboration.force')),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='TacticalCollaboration.reportrevision')),
            ],
        ),
        migrations.AddField(
            model_name='force',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TacticalCollaboration.organization'),
        ),
        migrations.CreateModel(
            name='ConnectionLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField(unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TacticalCollaboration.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommandReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=40)),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('request_id', models.UUIDField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TacticalCollaboration.organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='reportrevision',
            constraint=models.UniqueConstraint(fields=('report', 'version'), name='tactical_report_revision_unique'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['organization', 'updated_at'], name='tactical_report_org_time'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='tactical_membership_unique'),
        ),
        migrations.AddIndex(
            model_name='joinapplication',
            index=models.Index(fields=['organization', 'status'], name='tactical_application_state'),
        ),
        migrations.AddIndex(
            model_name='force',
            index=models.Index(fields=['organization', 'side'], name='tactical_force_org_side'),
        ),
        migrations.AddIndex(
            model_name='connectionlease',
            index=models.Index(fields=['organization', 'expires_at', 'user'], name='tactical_lease_org_expiry'),
        ),
        migrations.AddIndex(
            model_name='commandreceipt',
            index=models.Index(fields=['actor', 'created_at'], name='tactical_receipt_actor_time'),
        ),
        migrations.AddConstraint(
            model_name='commandreceipt',
            constraint=models.UniqueConstraint(fields=('actor', 'scope', 'request_id'), name='tactical_receipt_unique'),
        ),
    ]
