# Generated by Django 4.2.5 on 2026-09-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TacticalCollaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='force',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
