# Generated by Django 4.2.5 on 2026-09-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TacticalCollaboration', '0002_force_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionlease',
            name='socket_claim_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connectionlease',
            name='socket_claim_window_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='connectionlease',
            name='socket_generation',
            field=models.UUIDField(null=True),
        ),
    ]
