# Generated by Django 4.2.6 on 2024-06-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAuthGroup',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fraud_auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FraudAuthUserGroup',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fraud_auth_user_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FraudList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fraud_account', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('fraud_type', models.CharField(blank=True, max_length=255, null=True)),
                ('source_group_id', models.IntegerField(blank=True, null=True)),
                ('source_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fraud_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FraudOperationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('operation_type', models.CharField(blank=True, max_length=80, null=True)),
                ('fraud_account', models.CharField(blank=True, max_length=255, null=True)),
                ('operation_details', models.CharField(blank=True, max_length=255, null=True)),
                ('operating_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fraud_operation_details',
                'managed': False,
            },
        ),
    ]
