# Generated by Django 4.2.6 on 2024-05-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanetaryResource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlResourcePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pl_resource_price',
                'managed': False,
            },
        ),
    ]
