# Generated by Django 4.2.6 on 2024-05-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanetaryResource', '0002_plresourceprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSearchPlanetary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_ps_id', models.CharField(blank=True, db_column='region', max_length=255, null=True)),
                ('region_security', models.CharField(blank=True, max_length=255, null=True)),
                ('constellation_ps_id', models.CharField(blank=True, db_column='constellation', max_length=255, null=True)),
                ('constellation_security', models.CharField(blank=True, max_length=255, null=True)),
                ('solar_system_ps_id', models.CharField(blank=True, db_column='solar_system', max_length=255, null=True)),
                ('solar_system_security', models.CharField(blank=True, max_length=255, null=True)),
                ('planet_id', models.CharField(blank=True, max_length=15, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_yield', models.FloatField(blank=True, null=True)),
                ('resource_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pre_search_planetary',
                'managed': False,
            },
        ),
    ]
