# Generated by Django 4.2.6 on 2024-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanetaryResource', '0003_presearchplanetary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetaryProgramme',
            fields=[
                ('programme_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('programme_name', models.CharField(blank=True, max_length=255, null=True)),
                ('programme_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('programme_element', models.JSONField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planetary_programme',
                'managed': False,
            },
        ),
    ]
