export const fakeSearchData = [
  {
    key: "1",
    region: "伏尔戈",
    region_security: 0.8,
    constellation: "厄沙拉",
    constellation_security: 0.6,
    solar_system: "吉他",
    solar_system_security: 0.9,
    planet_id: "IV",
    resource_level: 1,
    resource_yield: 23.58,
    resource_name: "光彩合金",
  },
  {
    key: "2",
    region: "德里克",
    region_security: 0.7,
    constellation: "奥拉日",
    constellation_security: 0.4,
    solar_system: "欧图尼",
    solar_system_security: 0.7,
    planet_id: "III",
    resource_level: 3,
    resource_yield: 49.23,
    resource_name: "建筑模块",
  },
  {
    key: "3",
    region: "新地区1",
    region_security: 0.6,
    constellation: "星座1",
    constellation_security: 0.5,
    solar_system: "太阳系1",
    solar_system_security: 0.8,
    planet_id: "I",
    resource_level: 2,
    resource_yield: 31.45,
    resource_name: "能源晶体",
  },
  {
    key: "4",
    region: "新地区2",
    region_security: 0.75,
    constellation: "星座2",
    constellation_security: 0.3,
    solar_system: "太阳系2",
    solar_system_security: 0.65,
    planet_id: "II",
    resource_level: 1,
    resource_yield: 27.89,
    resource_name: "金属合金",
  },
  {
    key: "5",
    region: "新地区3",
    region_security: 0.85,
    constellation: "星座3",
    constellation_security: 0.7,
    solar_system: "太阳系3",
    solar_system_security: 0.9,
    planet_id: "V",
    resource_level: 3,
    resource_yield: 45.67,
    resource_name: "稀有元素",
  },
  {
    key: "6",
    region: "新地区4",
    region_security: 0.7,
    constellation: "星座4",
    constellation_security: 0.5,
    solar_system: "太阳系4",
    solar_system_security: 0.75,
    planet_id: "IV",
    resource_level: 2,
    resource_yield: 39.12,
    resource_name: "晶体矿石",
  },
  {
    key: "7",
    region: "新地区5",
    region_security: 0.8,
    constellation: "星座5",
    constellation_security: 0.6,
    solar_system: "太阳系5",
    solar_system_security: 0.85,
    planet_id: "III",
    resource_level: 4,
    resource_yield: 22.34,
    resource_name: "生物样本",
  },
  {
    key: "8",
    region: "新地区6",
    region_security: 0.65,
    constellation: "星座6",
    constellation_security: 0.4,
    solar_system: "太阳系6",
    solar_system_security: 0.7,
    planet_id: "II",
    resource_level: 3,
    resource_yield: 48.76,
    resource_name: "智能芯片",
  },
  {
    key: "9",
    region: "新地区7",
    region_security: 0.75,
    constellation: "星座7",
    constellation_security: 0.55,
    solar_system: "太阳系7",
    solar_system_security: 0.8,
    planet_id: "I",
    resource_level: 2,
    resource_yield: 36.21,
    resource_name: "纳米材料",
  },
  {
    key: "10",
    region: "新地区8",
    region_security: 0.7,
    constellation: "星座8",
    constellation_security: 0.45,
    solar_system: "太阳系8",
    solar_system_security: 0.75,
    planet_id: "V",
    resource_level: 4,
    resource_yield: 25.67,
    resource_name: "能量结晶",
  },
  {
    key: "11",
    region: "新地区9",
    region_security: 0.8,
    constellation: "星座9",
    constellation_security: 0.65,
    solar_system: "太阳系9",
    solar_system_security: 0.9,
    planet_id: "IV",
    resource_level: 4,
    resource_yield: 42.89,
    resource_name: "合成纤维",
  },
  {
    key: "12",
    region: "新地区10",
    region_security: 0.6,
    constellation: "星座10",
    constellation_security: 0.35,
    solar_system: "太阳系10",
    solar_system_security: 0.6,
    planet_id: "III",
    resource_level: 2,
    resource_yield: 33.78,
    resource_name: "晶体电池",
  },
  {
    key: "13",
    region: "新地区11",
    region_security: 0.9,
    constellation: "星座11",
    constellation_security: 0.8,
    solar_system: "太阳系11",
    solar_system_security: 0.95,
    planet_id: "II",
    resource_level: 1,
    resource_yield: 20.56,
    resource_name: "量子晶格",
  },
];

const columns = [
  {
    title: "Name",
    dataIndex: "name",
    filters: [
      {
        text: "Joe",
        value: "Joe",
      },
      {
        text: "Category 1",
        value: "Category 1",
      },
      {
        text: "Category 2",
        value: "Category 2",
      },
    ],
    filterMode: "tree",
    filterSearch: true,
    onFilter: (value, record) => record.name.includes(value),
    width: "30%",
  },
  {
    title: "Age",
    dataIndex: "age",
    sorter: (a, b) => a.age - b.age,
  },
  {
    title: "Address",
    dataIndex: "address",
    filters: [
      {
        text: "London",
        value: "London",
      },
      {
        text: "New York",
        value: "New York",
      },
    ],
    onFilter: (value, record) => record.address.startsWith(value),
    filterSearch: true,
    width: "40%",
  },
];
