# Generated by Django 4.2.5 on 2026-09-24 10:08

import Market.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('needs_auth', 'Needs authentication')], default='queued', max_length=16)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], max_length=16)),
                ('created_at_ms', models.BigIntegerField(default=Market.models.epoch_ms)),
                ('started_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('finished_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('lease_owner', models.CharField(blank=True, default='', max_length=128)),
                ('lease_expires_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_ms', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('min_interval_seconds', models.PositiveIntegerField(default=2100)),
                ('max_interval_seconds', models.PositiveIntegerField(default=3060)),
                ('enabled', models.BooleanField(default=True)),
                ('next_due_at_ms', models.BigIntegerField(blank=True, null=True)),
                ('session_status', models.CharField(choices=[('unconfigured', 'Unconfigured'), ('ready', 'Ready'), ('needs_auth', 'Needs authentication'), ('error', 'Error')], default='unconfigured', max_length=16)),
                ('updated_at_ms', models.BigIntegerField(default=Market.models.epoch_ms)),
            ],
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('scope', models.CharField(default='global', max_length=80)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LatestPrice',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='latest_price', serialize=False, to='Market.marketitem')),
                ('updated_at_ms', models.BigIntegerField(default=Market.models.epoch_ms)),
            ],
        ),
        migrations.CreateModel(
            name='MarketConfigAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('changed_at_ms', models.BigIntegerField(default=Market.models.epoch_ms)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='Market.marketconfig')),
            ],
            options={
                'ordering': ['-changed_at_ms', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('best_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('buy_order_count', models.PositiveIntegerField(default=0)),
                ('sell_order_count', models.PositiveIntegerField(default=0)),
                ('observed_at_ms', models.BigIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='Market.marketitem')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='Market.collectionrun')),
            ],
            options={
                'ordering': ['-observed_at_ms', '-id'],
                'indexes': [models.Index(fields=['item', '-observed_at_ms'], name='market_snapshot_item_time')],
            },
        ),
        migrations.AddConstraint(
            model_name='pricesnapshot',
            constraint=models.UniqueConstraint(fields=('run', 'item'), name='market_snapshot_run_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='pricesnapshot',
            constraint=models.CheckConstraint(check=models.Q(('best_buy__isnull', True), ('best_buy__gt', 0), _connector='OR'), name='market_snapshot_buy_positive'),
        ),
        migrations.AddConstraint(
            model_name='pricesnapshot',
            constraint=models.CheckConstraint(check=models.Q(('best_sell__isnull', True), ('best_sell__gt', 0), _connector='OR'), name='market_snapshot_sell_positive'),
        ),
        migrations.AddField(
            model_name='latestprice',
            name='snapshot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='latest_record', to='Market.pricesnapshot'),
        ),
        migrations.AddIndex(
            model_name='collectionrun',
            index=models.Index(fields=['status', 'created_at_ms'], name='market_run_status_created'),
        ),
    ]
