# Generated by Django 4.2.5 on 2026-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marketconfig',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='market_config_singleton_id'),
        ),
        migrations.AddConstraint(
            model_name='marketconfig',
            constraint=models.CheckConstraint(check=models.Q(('min_interval_seconds__gte', 2100), ('max_interval_seconds__lte', 3060), ('min_interval_seconds__lte', models.F('max_interval_seconds'))), name='market_config_interval_bounds'),
        ),
    ]
