# Generated by Django 4.2.5 on 2026-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_marketconfig_market_config_singleton_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='last_attempt_at_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='last_error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='last_failure_at_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
