# Generated by Django 4.2.5 on 2026-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_pricesnapshot_price_levels'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['item', 'observed_at_ms', 'id'], name='market_snap_item_obs_id'),
        ),
    ]
