# Generated by Django 4.2.5 on 2026-10-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_pricesnapshot_market_snap_item_obs_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketconfig',
            name='cooldown_until_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketconfig',
            name='rate_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketconfig',
            name='session_cursor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collectionrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed'), ('needs_auth', 'Needs authentication'), ('rate_limited', 'Rate limited')], default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='marketconfig',
            name='session_status',
            field=models.CharField(choices=[('unconfigured', 'Unconfigured'), ('ready', 'Ready'), ('needs_auth', 'Needs authentication'), ('error', 'Error'), ('cooldown', 'Rate-limit cooldown'), ('blocked', 'Service rejected')], default='unconfigured', max_length=16),
        ),
    ]
