# Generated by Django 4.2.5 on 2026-10-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0008_marketconfig_cooldown_until_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionrun',
            name='batch_fallback_reason',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='expected_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='item_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=40, null=True),
        ),
        migrations.AddField(
            model_name='marketconfig',
            name='batch_fallback_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='marketconfig',
            name='batch_fallback_until_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketconfig',
            name='capacity_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketconfig',
            name='max_items_per_run',
            field=models.PositiveSmallIntegerField(choices=[(40, '40'), (80, '80')], default=80),
        ),
        migrations.AddConstraint(
            model_name='marketconfig',
            constraint=models.CheckConstraint(check=models.Q(('max_items_per_run__in', [40, 80])), name='market_config_batch_bounds'),
        ),
    ]
