# Generated by Django 4.2.5 on 2026-10-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0009_paced_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionrun',
            name='item_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
