# Generated by Django 4.2.5 on 2026-09-20 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('server', models.CharField(default='cn', max_length=10)),
                ('name_key', models.CharField(max_length=64, unique=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('moderation_reason', models.CharField(blank=True, max_length=1000)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_corporations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(db_index=True, default='draft', max_length=12)),
                ('content', models.JSONField(default=dict)),
                ('activity_keys', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, max_length=1000)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Community.corporation')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Community.corporation')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Community.revision')),
            ],
        ),
        migrations.AddField(
            model_name='corporation',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Community.revision'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='working_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='Community.revision'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('statement', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=200)),
                ('status', models.CharField(db_index=True, default='pending', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Community.corporation')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('original_sha256', models.CharField(max_length=64)),
                ('storage_name', models.CharField(max_length=100, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=30)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Community.corporation')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['uploader', 'created_at'], name='community_media_actor_time')],
            },
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('uploader', 'request_id'), name='community_media_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='draftrequest',
            constraint=models.UniqueConstraint(fields=('author', 'request_id'), name='community_draft_request_unique'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['applicant', 'created_at'], name='community_claim_actor_time'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('applicant', 'request_id'), name='community_claim_request_unique'),
        ),
    ]
