# Generated by Django 4.2.5 on 2026-09-20 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUploadAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('original_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(default='processing', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Community.corporation')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['uploader', 'created_at'], name='community_attempt_actor_time')],
            },
        ),
        migrations.AddConstraint(
            model_name='mediauploadattempt',
            constraint=models.UniqueConstraint(fields=('uploader', 'request_id'), name='community_upload_attempt_unique'),
        ),
    ]
