# Generated by Django 4.2.5 on 2024-04-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('co_id', models.CharField(db_comment='星座ID', max_length=255, primary_key=True, serialize=False)),
                ('co_title', models.CharField(blank=True, db_comment='星座名称', max_length=255, null=True)),
                ('co_titleen', models.CharField(blank=True, db_column='co_titleEn', db_comment='星座英文名称', max_length=255, null=True)),
                ('co_desc', models.CharField(blank=True, db_comment='星座描述', max_length=800, null=True)),
                ('co_safetylvl', models.CharField(blank=True, db_column='co_safetyLvl', db_comment='星座安等', max_length=255, null=True)),
                ('co_creationdate', models.CharField(blank=True, db_column='co_creationDate', max_length=255, null=True)),
                ('co_creationuser_id', models.CharField(blank=True, db_column='co_creationUser_id', max_length=255, null=True)),
                ('co_updatedate', models.CharField(blank=True, db_column='co_updateDate', max_length=255, null=True)),
                ('co_updateuser_id', models.CharField(blank=True, db_column='co_updateUser_id', max_length=255, null=True)),
                ('co_sortorder', models.CharField(blank=True, db_column='co_sortOrder', max_length=255, null=True)),
            ],
            options={
                'db_table': 'constellation',
                'db_table_comment': '星座表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('r_id', models.CharField(db_comment='星域ID', max_length=255, primary_key=True, serialize=False)),
                ('r_title', models.CharField(blank=True, db_comment='星域名称', max_length=255, null=True)),
                ('r_titleen', models.CharField(blank=True, db_column='r_titleEn', db_comment='星域英文名称', max_length=255, null=True)),
                ('r_desc', models.CharField(blank=True, db_comment='星域描述', max_length=800, null=True)),
                ('r_safetylvl', models.CharField(blank=True, db_column='r_safetyLvl', db_comment='星域安等', max_length=255, null=True)),
                ('r_creationdate', models.CharField(blank=True, db_column='r_creationDate', max_length=255, null=True)),
                ('r_creationuser_id', models.CharField(blank=True, db_column='r_creationUser_id', max_length=255, null=True)),
                ('r_updatedate', models.CharField(blank=True, db_column='r_updateDate', max_length=255, null=True)),
                ('r_updateuser_id', models.CharField(blank=True, db_column='r_updateUser_id', max_length=255, null=True)),
                ('r_sortorder', models.CharField(blank=True, db_column='r_sortOrder', max_length=255, null=True)),
            ],
            options={
                'db_table': 'region',
                'db_table_comment': '星域表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solarsystem',
            fields=[
                ('ss_id', models.CharField(db_comment='星系ID', max_length=255, primary_key=True, serialize=False)),
                ('ss_title', models.CharField(blank=True, db_comment='星系名称', max_length=255, null=True)),
                ('ss_titleen', models.CharField(blank=True, db_column='ss_titleEn', db_comment='星系英文名称', max_length=255, null=True)),
                ('ss_desc', models.CharField(blank=True, db_comment='星系描述', max_length=800, null=True)),
                ('ss_safetylvl', models.CharField(blank=True, db_column='ss_safetyLvl', db_comment='星系安等', max_length=255, null=True)),
                ('ss_creationdate', models.CharField(blank=True, db_column='ss_creationDate', max_length=255, null=True)),
                ('ss_creationuser_id', models.CharField(blank=True, db_column='ss_creationUser_id', max_length=255, null=True)),
                ('ss_updatedate', models.CharField(blank=True, db_column='ss_updateDate', max_length=255, null=True)),
                ('ss_updateuser_id', models.CharField(blank=True, db_column='ss_updateUser_id', max_length=255, null=True)),
                ('ss_sortorder', models.CharField(blank=True, db_column='ss_sortOrder', max_length=255, null=True)),
                ('ss_cntstation', models.CharField(blank=True, db_column='ss_cntStation', max_length=255, null=True)),
                ('ss_ismarket', models.CharField(blank=True, db_column='ss_isMarket', max_length=255, null=True)),
            ],
            options={
                'db_table': 'solarsystem',
                'db_table_comment': '星座表',
                'managed': False,
            },
        ),
    ]
