# Generated by Django 4.2.5 on 2026-09-08 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('type', models.CharField(choices=[('feature', '功能建议'), ('bug', '问题反馈')], max_length=16)),
                ('module', models.CharField(choices=[('planetary', '行星资源'), ('starmap', '星图'), ('fraudlist', '避坑名单'), ('account', '账户'), ('other', '其他')], max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=5000)),
                ('contact', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('declined', '暂不采纳')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('body', models.TextField(max_length=3000)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Feedback.feedbackticket')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbackticket',
            index=models.Index(fields=['author', 'created_at'], name='feedback_ticket_rate_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbackticket',
            constraint=models.UniqueConstraint(fields=('author', 'request_id'), name='feedback_ticket_request_unique'),
        ),
        migrations.AddIndex(
            model_name='feedbackcomment',
            index=models.Index(fields=['author', 'created_at'], name='feedback_comment_rate_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbackcomment',
            constraint=models.UniqueConstraint(fields=('author', 'request_id'), name='feedback_comment_request_unique'),
        ),
    ]
