# Generated by Django 4.2.5 on 2026-09-08 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('storage_name', models.CharField(max_length=100, unique=True)),
                ('size', models.PositiveIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_attachments', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='Feedback.feedbackticket')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['author', 'created_at'], name='feedback_attach_rate_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='feedbackattachment',
            constraint=models.UniqueConstraint(fields=('author', 'request_id'), name='feedback_attach_request_unique'),
        ),
    ]
